export const packages = [
  {
    name: "Starter",
    cost: 250,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilisnam, facere nemo vitae mollitia consequatur! Quasi exercitationemullam nihil ea perspiciatis quidem tempore sit temporibus. Officiis, qui ipsam. Animi, recusandae.",
    features: [
      {
        title: "Logo transparency",
        active: true,
      },
      {
        title: "High resolution",
        active: true,
      },
      {
        title: "Vector file",
        active: false,
      },
      {
        title: "initial concept",
        quantity: 2,
        active: true,
      },
      {
        title: "Include source code",
        active: true,
      },
      {
        title: "Revisions",
        quantity: 1,
        active: true,
      },
      {
        title: "revisions",
        quantity: 2,
        active: true,
      },
      {
        title: "delivery time",
        quantity: "2 days",
        active: true,
      },
    ],
    additionalFeatures: {
      additionalRevision: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      includedSocialKit: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      contentUpload: {
        details: "This requires 1 more days to complete",
        additionalCost: 50,
      },
      stationaryDesign: {
        details: "This requires 2 more days to complete",
        additionalCost: 80,
      },
      hugeSizeFile: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      additionalLogoConcept: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      include3DVision: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      bussinessCard: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      fastDelivery: {
        time: 1,
        additionalCost: 100,
      },
    },
  },
  {
    name: "Popular",
    cost: 450,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilisnam, facere nemo vitae mollitia consequatur! Quasi exercitationemullam nihil ea perspiciatis quidem tempore sit temporibus. Officiis, qui ipsam. Animi, recusandae.",
    features: [
      {
        title: "Logo transparency",
        active: true,
      },
      {
        title: "High resolution",
        active: true,
      },
      {
        title: "Vector file",
        active: true,
      },
      {
        title: "initial concept",
        quantity: 2,
        active: true,
      },
      {
        title: "revisions",
        quantity: 5,
        active: true,
      },
      {
        title: "delivery time",
        quantity: "2 days",
        active: true,
      },
    ],
    additionalFeatures: {
      additionalRevision: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      includedSocialKit: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      contentUpload: {
        details: "This requires 1 more days to complete",
        additionalCost: 50,
      },
      stationaryDesign: {
        details: "This requires 2 more days to complete",
        additionalCost: 80,
      },
      hugeSizeFile: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      additionalLogoConcept: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      include3DVision: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      bussinessCard: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      fastDelivery: {
        time: 1,
        additionalCost: 350,
      },
    },
  },
  {
    name: "Premium",
    cost: 900,
    details: "",
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilisnam, facere nemo vitae mollitia consequatur! Quasi exercitationemullam nihil ea perspiciatis quidem tempore sit temporibus. Officiis, qui ipsam. Animi, recusandae.",
    features: [
      {
        title: "Logo transparency",
        active: true,
      },
      {
        title: "High resolution",
        active: true,
      },
      {
        title: "Vector file",
        active: true,
      },
      {
        title: "initial concept",
        quantity: 4,
        active: true,
      },
      {
        title: "revisions",
        quantity: "Unlimited",
        active: true,
      },
      {
        title: "delivery time",
        quantity: "2 days",
        active: true,
      },
    ],
    additionalFeatures: {
      additionalRevision: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      includedSocialKit: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      contentUpload: {
        details: "This requires 1 more days to complete",
        additionalCost: 50,
      },
      stationaryDesign: {
        details: "This requires 2 more days to complete",
        additionalCost: 80,
      },
      hugeSizeFile: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      additionalLogoConcept: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      include3DVision: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      bussinessCard: {
        details: "This requires 2 more days to complete",
        additionalCost: 100,
      },
      fastDelivery: {
        time: 1,
        additionalCost: 500,
      },
    },
  },
];

export const sellerSliderData = [
  {
    url: "https://api.lorem.space/image/car?w=1000&h=600",
    thumbnail: "https://api.lorem.space/image/car?w=250&h=150",
    type: "img",
  },
  {
    url: "https://api.lorem.space/image/car?w=1000&h=600",
    thumbnail: "https://api.lorem.space/image/car?w=250&h=150",
    type: "img",
  },
  {
    url: "https://api.lorem.space/image/car?w=1000&h=600",
    thumbnail: "https://api.lorem.space/image/car?w=250&h=150",
    type: "img",
  },
  {
    url: "https://api.lorem.space/image/car?w=1000&h=600",
    thumbnail: "https://api.lorem.space/image/car?w=250&h=150",
    type: "img",
  },
  {
    url: "https://api.lorem.space/image/car?w=1000&h=600",
    thumbnail: "https://api.lorem.space/image/car?w=250&h=150",
    type: "img",
  },
  {
    url: "https://api.lorem.space/image/car?w=1000&h=600",
    thumbnail: "https://api.lorem.space/image/car?w=250&h=150",
    type: "img",
  },
  {
    thumbnail: "https://api.lorem.space/image/car?w=250&h=150",
    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    type: "video",
  },
];

export const reviews = [
  {
    id: 0,
    rating: 5,
    img: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    text: "Realy appreciate his work he is fast indeed. Realy appreciate his work he is fast indeed",
    reply: "",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
  },
  {
    id: 1,
    rating: 5,
    img: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    text: "Realy appreciate his work he is fast indeed. Realy appreciate his work he is fast indeed",
    reply: "",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
  },
  {
    id: 2,
    rating: 5,
    img: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    text: "Realy appreciate his work he is fast indeed. Realy appreciate his work he is fast indeed",
    reply: "",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
  },
  {
    id: 3,
    rating: 5,
    img: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    text: "Realy appreciate his work he is fast indeed. Realy appreciate his work he is fast indeed",
    reply: "",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
  },
  {
    id: 4,
    rating: 5,
    img: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    text: "Realy appreciate his work he is fast indeed. Realy appreciate his work he is fast indeed",
    reply: "Thanks for your trust and belive.",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
  },
  {
    id: 5,
    rating: 5,
    img: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    text: "Realy appreciate his work he is fast indeed. Realy appreciate his work he is fast indeed",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
  },
  {
    id: 6,
    rating: 5,
    img: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    text: "Realy appreciate his work he is fast indeed. Realy appreciate his work he is fast indeed",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
  },
  {
    id: 7,
    rating: 5,
    img: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    text: "Realy appreciate his work he is fast indeed. Realy appreciate his work he is fast indeed",
    reply: "Thanks for your trust and belive.",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
  },
];

export const biddingTypes = [
  { value: 1, label: "Fixed Budget Price" },
  { value: 2, label: "Hourly Pricing" },
  { value: 3, label: "Bidding Price" },
];

// !NOTE: This is just a sample data for the demo purpose of chat
export const chat = [
  {
    userId: 1,
    type: "text",
    userName: "Kursat",
    text: "Give me a message list example !",
  },
  {
    userId: 2,
    type: "text",
    userName: "Emre",
    text: "Hi there how are you doing I thought ",
  },
  {
    userId: 3,
    type: "text",
    userName: "Kursat",
    text: "Give me a message list example !",
  },
  {
    userId: 4,
    type: "text",
    userName: "Emre",
    text: "Hi there how are you doing I thought ",
  },
  {
    userId: 1,
    type: "text",
    userName: "Kursat",
    text: "Give me a message list example !",
  },
  {
    userId: 2,
    type: "text",
    userName: "Emre",
    text: "Hi there how are you doing I thought ",
  },
  {
    userId: 3,
    type: "text",
    userName: "Kursat",
    text: "Give me a message list example !",
  },
  {
    userId: 3,
    type: "text",
    userName: "Emre",
    text: "Hi there how are you doing I thought ",
  },
  {
    userId: 2,
    type: "text",
    userName: "Kursat",
    text: "Give me a message list example !",
  },
  {
    userId: 1,
    type: "file",
    userName: "Emre",
    text: "Hi there how are you doing I thought ",
    data: {
      uri: "https://www.sample-videos.com/pdf/Sample-pdf-5mb.pdf",
      status: {
        click: false,
      },
    },
  },
  {
    userId: 2,
    type: "text",
    userName: "Kursat",
    text: "Give me a message list example hey there how are you. I thought you were dead or some thing !",
  },
  {
    userId: 4,
    type: "video",
    userName: "Emre",
    text: "Hi there how are you doing I thought ",
    data: {
      videoURL:
        "https://www.sample-videos.com/video123/mp4/240/big_buck_bunny_240p_1mb.mp4",
      status: {
        download: true,
      },
    },
  },
  {
    userId: 2,
    type: "photo",
    userName: "Kursat",
    text: "Give me a message list example !",
    data: {
      uri: "https://api.lorem.space/image/face?w=2000&h=2000&hash=qecd5c51",
    },
  },
  {
    userId: 1,
    type: "audio",
    userName: "Emre",
    text: "Hi there how are you doing I thought ",
    data: {
      audioURL: "https://www.sample-videos.com/audio/mp3/crowd-cheering.mp3",
    },
  },
];

export const favData = [
  {
    userName: "Kursat",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "Web Developer",
    location: "Istanbul, Turkey",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 100,
    eBudget: 500,
    willExpireIn: 5,
    perposals: 8,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Emre",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "PHP Developer",
    location: "USA, New York",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 200,
    eBudget: 600,
    willExpireIn: 2,
    perposals: 5,
    jobType: "Hourly",
    isFavorite: true,
  },
  {
    userName: "Umer",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "IOS Developer",
    location: "Pakistan, Lahore",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 300,
    eBudget: 700,
    willExpireIn: 3,
    perposals: 3,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Kursat",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "Web Developer",
    location: "Istanbul, Turkey",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 100,
    eBudget: 500,
    willExpireIn: 5,
    perposals: 8,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Talha",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "UI Designer",
    location: "Pakistan, Lahore",
    skill: ["Abode", "Web Design", "UI/UX Designer"],
    sBudget: 300,
    eBudget: 700,
    willExpireIn: 3,
    perposals: 3,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Kursat",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "Web Developer",
    location: "Istanbul, Turkey",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 100,
    eBudget: 500,
    willExpireIn: 5,
    perposals: 8,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Emre",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "PHP Developer",
    location: "USA, New York",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 200,
    eBudget: 600,
    willExpireIn: 2,
    perposals: 5,
    jobType: "Hourly",
    isFavorite: true,
  },
  {
    userName: "Kursat",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "Web Developer",
    location: "Istanbul, Turkey",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 100,
    eBudget: 500,
    willExpireIn: 5,
    perposals: 8,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Emre",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "PHP Developer",
    location: "USA, New York",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 200,
    eBudget: 600,
    willExpireIn: 2,
    perposals: 5,
    jobType: "Hourly",
    isFavorite: true,
  },
  {
    userName: "Umer",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "IOS Developer",
    location: "Pakistan, Lahore",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 300,
    eBudget: 700,
    willExpireIn: 3,
    perposals: 3,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Kursat",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "Web Developer",
    location: "Istanbul, Turkey",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 100,
    eBudget: 500,
    willExpireIn: 5,
    perposals: 8,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Talha",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "UI Designer",
    location: "Pakistan, Lahore",
    skill: ["Abode", "Web Design", "UI/UX Designer"],
    sBudget: 300,
    eBudget: 700,
    willExpireIn: 3,
    perposals: 3,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Kursat",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "Web Developer",
    location: "Istanbul, Turkey",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 100,
    eBudget: 500,
    willExpireIn: 5,
    perposals: 8,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Emre",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "PHP Developer",
    location: "USA, New York",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 200,
    eBudget: 600,
    willExpireIn: 2,
    perposals: 5,
    jobType: "Hourly",
    isFavorite: true,
  },
  {
    userName: "Kursat",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "Web Developer",
    location: "Istanbul, Turkey",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 100,
    eBudget: 500,
    willExpireIn: 5,
    perposals: 8,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Emre",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "PHP Developer",
    location: "USA, New York",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 200,
    eBudget: 600,
    willExpireIn: 2,
    perposals: 5,
    jobType: "Hourly",
    isFavorite: true,
  },
  {
    userName: "Umer",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "IOS Developer",
    location: "Pakistan, Lahore",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 300,
    eBudget: 700,
    willExpireIn: 3,
    perposals: 3,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Kursat",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "Web Developer",
    location: "Istanbul, Turkey",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 100,
    eBudget: 500,
    willExpireIn: 5,
    perposals: 8,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Talha",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "UI Designer",
    location: "Pakistan, Lahore",
    skill: ["Abode", "Web Design", "UI/UX Designer"],
    sBudget: 300,
    eBudget: 700,
    willExpireIn: 3,
    perposals: 3,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Kursat",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "Web Developer",
    location: "Istanbul, Turkey",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 100,
    eBudget: 500,
    willExpireIn: 5,
    perposals: 8,
    jobType: "Fixed",
    isFavorite: true,
  },
  {
    userName: "Emre",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    mainSkill: "PHP Developer",
    location: "USA, New York",
    skill: ["Web Developer", "Mobile Developer", "UI/UX Designer"],
    sBudget: 200,
    eBudget: 600,
    willExpireIn: 2,
    perposals: 5,
    jobType: "Hourly",
    isFavorite: true,
  },
]

export const sReviews = [
  {
    userName: "Ali Akbar",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    reviewTitle: "Fast and clear.",
    reiewDescription: "Fast and clear. European visual concepts. Easy to communicate TOP",
    stars: 4,
    reviewDate: "2020-10-10",
  },
  {
    userName: "HaseeB Shah",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    reviewTitle: "This seller was great overall.",
    reiewDescription: "This seller was great overall. He was very responsive and delivered the project on time. I would definitely work with him again.",
    stars: 5,
    reviewDate: "2020-10-10",
  },
  {
    userName: "Muntha Iqbal",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    reviewTitle: "Great work, great communication.",
    reiewDescription: "Great work, great communication. I will definitely work with him again.",
    stars: 5,
    reviewDate: "2020-10-10",
  },
  {
    userName: "Ibrahim",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    reviewTitle: "Great work, great communication.",
    reiewDescription: "Great help given and work was done as asked on time! :)",
    stars: 5,
    reviewDate: "2022-10-10",
  },
  {
    userName: "Faizan",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    reviewTitle: "Fast and clear.",
    reiewDescription: "Fast and clear. European visual concepts. Easy to communicate TOP",
    stars: 4,
    reviewDate: "2020-10-10",
  },
  {
    userName: "Ali Akbar",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    reviewTitle: "Fast and clear.",
    reiewDescription: "Fast and clear. European visual concepts. Easy to communicate TOP",
    stars: 4,
    reviewDate: "2020-10-10",
  },
  {
    userName: "HaseeB Shah",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    reviewTitle: "This seller was great overall.",
    reiewDescription: "This seller was great overall. He was very responsive and delivered the project on time. I would definitely work with him again.",
    stars: 5,
    reviewDate: "2020-10-10",
  },
  {
    userName: "Muntha Iqbal",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    reviewTitle: "Great work, great communication.",
    reiewDescription: "Great work, great communication. I will definitely work with him again.",
    stars: 5,
    reviewDate: "2020-10-10",
  },
  {
    userName: "Ibrahim",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    reviewTitle: "Great work, great communication.",
    reiewDescription: "Great help given and work was done as asked on time! :)",
    stars: 5,
    reviewDate: "2022-10-10",
  },
  {
    userName: "Faizan",
    userImg: "https://api.lorem.space/image/face?w=100&h=100&hash=qecd5c51",
    reviewTitle: "Fast and clear.",
    reiewDescription: "Fast and clear. European visual concepts. Easy to communicate TOP",
    stars: 4,
    reviewDate: "2020-10-10",
  },
]







