export const allProject = [
    {
        id: 1,
        title: " Website Designer Required For Directory Theme",
        category: " Web, Mobile & Software Dev",
        pricingType: "Fixed Price",
        budget: 100,
        hiredOn: "20-10-2022",
        // noOfPerposals will always be 0 unless approval status is true and some has bidded on it
        noOfPerposals: 10,
        // approval status will be true if project is approved by admin else false # Pending Screen
        approvalStatus: true,
        // project status will be closed if project is completed else open # Ongoing Screen # complted Screen
        projectStatus: "open",
        // if someone is hired for this project then hired status will be true else false # Ongoing Screen # complted Screen
        hiredStatus: true,
        // image url if hiredStatus is true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        // userName of hired person if hiredStatus is true,
        userName: "John Doe",
        // if project is complete then complete status will be true else false # complted Screen
        completeStatus: true,
        // if project is complete status is true then rating will be given by employer else 0 # complted Screen
        ratingValue: 4,
        cancelledStatus: true,
        days: 10,
        experties: ["Logo Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: " I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",

    },
    {
        id: 2,
        title: " I need a Website for my company",
        category: " Web Design",
        pricingType: "Hourly Pricing",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: false,
        userName: "John Doe",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-02.jpg",
        budget: 200,
        days: 20,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: " I need a Website for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",

    },
    {
        id: 3,
        title: " I need machine learning expert",
        category: " Machine Learning",
        pricingType: "Fixed Price",
        projectStatus: "open",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: true,

        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 300,
        days: 30,
        experties: ["Machine Learning", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: " I need machine learning expert Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, ten",

    },
    {
        id: 4,
        title: " PHP Laravel Developer Required (Contractual Employement)",
        category: "Web Development",
        pricingType: "Hourly Pricing",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 400,
        days: 40,
        experties: ["PHP", "Laravel", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: " PHP Laravel Developer Required (Contractual Employement) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",

    },
    {
        id: 5,
        title: "Landing Page Redesign / Sales Page Redesign (Not Entire Web)",
        category: "Web Design",
        pricingType: "Fixed Price",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: true,
        hiredStatus: false,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: true,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 500,
        days: 50,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: "Landing Page Redesign / Sales Page Redesign (Not Entire Web) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",

    },
    {
        id: 6,
        title: " I need machine learning expert",
        category: " Machine Learning",
        pricingType: "Fixed Price",
        projectStatus: "open",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: true,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 600,
        days: 60,
        experties: ["Machine Learning", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: " I need machine learning expert Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, ten",

    },
    {
        id: 7,
        title: " PHP Laravel Developer Required (Contractual Employement)",
        category: "Web Development",
        pricingType: "Hourly Pricing",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: true,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 700,
        days: 70,
        experties: ["PHP", "Laravel", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: " PHP Laravel Developer Required (Contractual Employement) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",

    },
    {
        id: 80,
        title: "Landing Page Redesign / Sales Page Redesign (Not Entire Web)",
        category: "Web Design",
        pricingType: "Fixed Price",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: true,
        hiredStatus: false,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: true,
        cancelledStatus: false,
        ratingValue: 4,
        budget: 8000,
        days: 800,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: "Landing Page Redesign / Sales Page Redesign (Not Entire Web) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",

    },
    {
        id: 9,
        title: " Website Designer Required For Directory Theme",
        category: " Web, Mobile & Software Dev",
        projectStatus: "open",
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: false,
        userName: "John Doe",
        completeStatus: true,
        cancelledStatus: false,
        ratingValue: 4,
        pricingType: "Fixed Price",
        budget: 900,
        days: 90,
        experties: ["Logo Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: " I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",

    },
    {
        id: 10,
        title: " I need a Website for my company",
        category: " Web Design",
        pricingType: "Hourly Pricing",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: true,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: true,
        cancelledStatus: false,
        ratingValue: 4,
        budget: 1000,
        days: 100,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: " I need a Website for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",

    },
    {
        id: 13,
        title: " PHP Laravel Developer Required (Contractual Employement)",
        category: "Web Development",
        pricingType: "Hourly Pricing",
        budget: 1300,
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: false,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: true,
        cancelledStatus: false,
        ratingValue: 4,

        days: 130,
        experties: ["PHP", "Laravel", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: " PHP Laravel Developer Required (Contractual Employement) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",

    },
    {
        id: 14,
        title: "Landing Page Redesign / Sales Page Redesign (Not Entire Web)",
        category: "Web Design",
        pricingType: "Fixed Price",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: true,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 1400,
        days: 1400,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: "Landing Page Redesign / Sales Page Redesign (Not Entire Web) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",

    },
    {
        id: 15,
        title: " PHP Laravel Developer Required (Contractual Employement)",
        category: "Web Development",
        pricingType: "Hourly Pricing",
        projectStatus: "open",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 1500,
        days: 150,
        experties: ["PHP", "Laravel", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: " PHP Laravel Developer Required (Contractual Employement) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
    },
    {
        id: 16,
        title: "Landing Page Redesign / Sales Page Redesign (Not Entire Web)",
        category: "Web Design",
        pricingType: "Fixed Price",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        noOfPerposals: 10,
        approvalStatus: true,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 1600,
        days: 160,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        description: "Landing Page Redesign / Sales Page Redesign (Not Entire Web) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",

    },
]

