export const allProject = [
    {
        id: 1,
        title: " Website Designer Required For Directory Theme",
        category: " Web, Mobile & Software Dev",
        pricingType: "Fixed Price",
        budget: 100,
        hiredOn: "20-10-2022",
        //empolyer Joining Date if there is one
        eJoiningDate: "10-01-2018",
        //perposal Accepting Date if it is accepted
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "10-09-2022",
        //empolyer rating if there is one
        eRating: 4,

        // noOfPerposals will always be 0 unless approval status is true and some has bidded on it
        noOfPerposals: 10,
        // approval status will be true if project is approved by admin else false # Pending Screen
        approvalStatus: true,
        // project status will be closed if project is completed else open # Ongoing Screen # complted Screen
        projectStatus: "open",
        // if someone is hired for this project then hired status will be true else false # Ongoing Screen # complted Screen
        hiredStatus: true,
        // image url if hiredStatus is true
        // freelancer Image
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        // Employer/ Client Image url
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        // userName of freelancer if hiredStatus is true,
        userName: "John Doe",
        // userName of empolyer/Client
        eUserName: "Umer Abid",
        // if project is complete then complete status will be true else false # complted Screen
        completeStatus: true,
        // if project is complete status is true then rating will be given by employer else 0 # complted Screen
        ratingValue: 4,
        cancelledStatus: true,
        days: 10,
        experties: ["Logo Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: " I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
        perposalDes: ""
    },
    {
        id: 2,
        title: " I need a Website for my company",
        category: " Web Design",
        pricingType: "Hourly Pricing",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: false,
        //freelancer username
        userName: "John Doe",
        eUserName: "Umer Abid",
        //empolyer/Client UserNAME
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-02.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        budget: 200,
        days: 20,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: " I need a Website for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 3,
        title: " I need machine learning expert",
        category: " Machine Learning",
        pricingType: "Fixed Price",
        projectStatus: "open",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "",
        eRating: 4,
        noOfPerposals: 10,
        approvalStatus: true,

        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 300,
        days: 30,
        experties: ["Machine Learning", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: " I need machine learning expert Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, ten",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 4,
        title: " PHP Laravel Developer Required (Contractual Employement)",
        category: "Web Development",
        pricingType: "Hourly Pricing",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 400,
        days: 40,
        experties: ["PHP", "Laravel", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: " PHP Laravel Developer Required (Contractual Employement) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 5,
        title: "Landing Page Redesign / Sales Page Redesign (Not Entire Web)",
        category: "Web Design",
        pricingType: "Fixed Price",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: true,
        hiredStatus: false,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: true,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 500,
        days: 50,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: "Landing Page Redesign / Sales Page Redesign (Not Entire Web) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 6,
        title: " I need machine learning expert",
        category: " Machine Learning",
        pricingType: "Fixed Price",
        projectStatus: "open",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: true,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 600,
        days: 60,
        experties: ["Machine Learning", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: " I need machine learning expert Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, ten",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 7,
        title: " PHP Laravel Developer Required (Contractual Employement)",
        category: "Web Development",
        pricingType: "Hourly Pricing",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: true,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 700,
        days: 70,
        experties: ["PHP", "Laravel", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: " PHP Laravel Developer Required (Contractual Employement) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 80,
        title: "Landing Page Redesign / Sales Page Redesign (Not Entire Web)",
        category: "Web Design",
        pricingType: "Fixed Price",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: true,
        hiredStatus: false,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: true,
        cancelledStatus: false,
        ratingValue: 4,
        budget: 8000,
        days: 800,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: "Landing Page Redesign / Sales Page Redesign (Not Entire Web) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 9,
        title: " Website Designer Required For Directory Theme",
        category: " Web, Mobile & Software Dev",
        projectStatus: "open",
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: false,
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: true,
        cancelledStatus: false,
        ratingValue: 4,
        pricingType: "Fixed Price",
        budget: 900,
        days: 90,
        experties: ["Logo Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: " I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 10,
        title: " I need a Website for my company",
        category: " Web Design",
        pricingType: "Hourly Pricing",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: true,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: true,
        cancelledStatus: false,
        ratingValue: 4,
        budget: 1000,
        days: 100,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: " I need a Website for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 13,
        title: " PHP Laravel Developer Required (Contractual Employement)",
        category: "Web Development",
        pricingType: "Hourly Pricing",
        budget: 1300,
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: false,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: true,
        cancelledStatus: false,
        ratingValue: 4,

        days: 130,
        experties: ["PHP", "Laravel", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: " PHP Laravel Developer Required (Contractual Employement) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 14,
        title: "Landing Page Redesign / Sales Page Redesign (Not Entire Web)",
        category: "Web Design",
        pricingType: "Fixed Price",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: true,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        fImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 1400,
        days: 1400,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: "Landing Page Redesign / Sales Page Redesign (Not Entire Web) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 15,
        title: " PHP Laravel Developer Required (Contractual Employement)",
        category: "Web Development",
        pricingType: "Hourly Pricing",
        projectStatus: "open",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: false,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 1500,
        days: 150,
        experties: ["PHP", "Laravel", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: " PHP Laravel Developer Required (Contractual Employement) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
    {
        id: 16,
        title: "Landing Page Redesign / Sales Page Redesign (Not Entire Web)",
        category: "Web Design",
        pricingType: "Fixed Price",
        projectStatus: "closed",
        hiredOn: "20-10-2022",
        eJoiningDate: "10-01-2018",
        perposalAcceptanceDate: "11-09-2021",
        projectPostDate: "11-09-2021",
        eRating: 4,

        noOfPerposals: 10,
        approvalStatus: true,
        hiredStatus: true,
        imageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        eImageURL: "https://kofejob.dreamguystech.com/template/assets/img/developer/developer-01.jpg",
        userName: "John Doe",
        eUserName: "Umer Abid",
        completeStatus: false,
        cancelledStatus: true,
        ratingValue: 4,
        budget: 1600,
        days: 160,
        experties: ["Web Design", "Graphic Design", "Illustrator", "Photoshop"],
        links: ["https://www.google.com", "https://www.google.com", "https://www.google.com"],
        projectdes: "Landing Page Redesign / Sales Page Redesign (Not Entire Web) Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplic",
        perposalDes: "I need a logo for my company Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis neque accusantium natus non, tenetur ipsum facilis molestiae exexplicabo nemo, amet molestias deserunt eaque et consequuntur magninulla aperiam nisi.",
    },
]

