export const gigCategories = [
    { value: '1', label: 'Web Development' },
    { value: '2', label: 'Mobile Development' },
    { value: '3', label: 'Desktop Development' },
    { value: '4', label: 'Data Science' },
    { value: '5', label: 'Machine Learning' },
    { value: '6', label: 'Artificial Intelligence' },
    { value: '7', label: 'Cloud Computing' },
    { value: '8', label: 'Cyber Security' },
    { value: '9', label: 'Blockchain' },
    { value: '10', label: 'Internet of Things' },
    { value: '11', label: 'Game Development' },
    { value: '12', label: 'UI/UX Design' },
    { value: '13', label: 'Graphic Design' },
    { value: '14', label: 'Video Editing' },
    { value: '15', label: 'Animation' },
    { value: '16', label: 'Digital Marketing' },
    { value: '17', label: 'Content Writing' },
    { value: '18', label: 'Business' },
    { value: '19', label: 'Other' },
]
const languages_list = {
    "af": "Afrikaans",
    "sq": "Albanian - shqip",
    "am": "Amharic - አማርኛ",
    "ar": "Arabic - العربية",
    "an": "Aragonese - aragonés",
    "hy": "Armenian - հայերեն",
    "ast": "Asturian - asturianu",
    "az": "Azerbaijani - azərbaycan dili",
    "eu": "Basque - euskara",
    "be": "Belarusian - беларуская",
    "bn": "Bengali - বাংলা",
    "bs": "Bosnian - bosanski",
    "br": "Breton - brezhoneg",
    "bg": "Bulgarian - български",
    "ca": "Catalan - català",
    "ckb": "Central Kurdish - کوردی (دەستنوسی عەرەبی)",
    "zh": "Chinese - 中文",
    "zh-HK": "Chinese (Hong Kong) - 中文（香港）",
    "zh-CN": "Chinese (Simplified) - 中文（简体）",
    "zh-TW": "Chinese (Traditional) - 中文（繁體）",
    "co": "Corsican",
    "hr": "Croatian - hrvatski",
    "cs": "Czech - čeština",
    "da": "Danish - dansk",
    "nl": "Dutch - Nederlands",
    "en": "English",
    "en-AU": "English (Australia)",
    "en-CA": "English (Canada)",
    "en-IN": "English (India)",
    "en-NZ": "English (New Zealand)",
    "en-ZA": "English (South Africa)",
    "en-GB": "English (United Kingdom)",
    "en-US": "English (United States)",
    "eo": "Esperanto - esperanto",
    "et": "Estonian - eesti",
    "fo": "Faroese - føroyskt",
    "fil": "Filipino",
    "fi": "Finnish - suomi",
    "fr": "French - français",
    "fr-CA": "French (Canada) - français (Canada)",
    "fr-FR": "French (France) - français (France)",
    "fr-CH": "French (Switzerland) - français (Suisse)",
    "gl": "Galician - galego",
    "ka": "Georgian - ქართული",
    "de": "German - Deutsch",
    "de-AT": "German (Austria) - Deutsch (Österreich)",
    "de-DE": "German (Germany) - Deutsch (Deutschland)",
    "de-LI": "German (Liechtenstein) - Deutsch (Liechtenstein)",
    "de-CH": "German (Switzerland) - Deutsch (Schweiz)",
    "el": "Greek - Ελληνικά",
    "gn": "Guarani",
    "gu": "Gujarati - ગુજરાતી",
    "ha": "Hausa",
    "haw": "Hawaiian - ʻŌlelo Hawaiʻi",
    "he": "Hebrew - עברית",
    "hi": "Hindi - हिन्दी",
    "hu": "Hungarian - magyar",
    "is": "Icelandic - íslenska",
    "id": "Indonesian - Indonesia",
    "ia": "Interlingua",
    "ga": "Irish - Gaeilge",
    "it": "Italian - italiano",
    "it-IT": "Italian (Italy) - italiano (Italia)",
    "it-CH": "Italian (Switzerland) - italiano (Svizzera)",
    "ja": "Japanese - 日本語",
    "kn": "Kannada - ಕನ್ನಡ",
    "kk": "Kazakh - қазақ тілі",
    "km": "Khmer - ខ្មែរ",
    "ko": "Korean - 한국어",
    "ku": "Kurdish - Kurdî",
    "ky": "Kyrgyz - кыргызча",
    "lo": "Lao - ລາວ",
    "la": "Latin",
    "lv": "Latvian - latviešu",
    "ln": "Lingala - lingála",
    "lt": "Lithuanian - lietuvių",
    "mk": "Macedonian - македонски",
    "ms": "Malay - Bahasa Melayu",
    "ml": "Malayalam - മലയാളം",
    "mt": "Maltese - Malti",
    "mr": "Marathi - मराठी",
    "mn": "Mongolian - монгол",
    "ne": "Nepali - नेपाली",
    "no": "Norwegian - norsk",
    "nb": "Norwegian Bokmål - norsk bokmål",
    "nn": "Norwegian Nynorsk - nynorsk",
    "oc": "Occitan",
    "or": "Oriya - ଓଡ଼ିଆ",
    "om": "Oromo - Oromoo",
    "ps": "Pashto - پښتو",
    "fa": "Persian - فارسی",
    "pl": "Polish - polski",
    "pt": "Portuguese - português",
    "pt-BR": "Portuguese (Brazil) - português (Brasil)",
    "pt-PT": "Portuguese (Portugal) - português (Portugal)",
    "pa": "Punjabi - ਪੰਜਾਬੀ",
    "qu": "Quechua",
    "ro": "Romanian - română",
    "mo": "Romanian (Moldova) - română (Moldova)",
    "rm": "Romansh - rumantsch",
    "ru": "Russian - русский",
    "gd": "Scottish Gaelic",
    "sr": "Serbian - српски",
    "sh": "Serbo-Croatian - Srpskohrvatski",
    "sn": "Shona - chiShona",
    "sd": "Sindhi",
    "si": "Sinhala - සිංහල",
    "sk": "Slovak - slovenčina",
    "sl": "Slovenian - slovenščina",
    "so": "Somali - Soomaali",
    "st": "Southern Sotho",
    "es": "Spanish - español",
    "es-AR": "Spanish (Argentina) - español (Argentina)",
    "es-419": "Spanish (Latin America) - español (Latinoamérica)",
    "es-MX": "Spanish (Mexico) - español (México)",
    "es-ES": "Spanish (Spain) - español (España)",
    "es-US": "Spanish (United States) - español (Estados Unidos)",
    "su": "Sundanese",
    "sw": "Swahili - Kiswahili",
    "sv": "Swedish - svenska",
    "tg": "Tajik - тоҷикӣ",
    "ta": "Tamil - தமிழ்",
    "tt": "Tatar",
    "te": "Telugu - తెలుగు",
    "th": "Thai - ไทย",
    "ti": "Tigrinya - ትግርኛ",
    "to": "Tongan - lea fakatonga",
    "tr": "Turkish - Türkçe",
    "tk": "Turkmen",
    "tw": "Twi",
    "uk": "Ukrainian - українська",
    "ur": "Urdu - اردو",
    "ug": "Uyghur",
    "uz": "Uzbek - o‘zbek",
    "vi": "Vietnamese - Tiếng Việt",
    "wa": "Walloon - wa",
    "cy": "Welsh - Cymraeg",
    "fy": "Western Frisian",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "yo": "Yoruba - Èdè Yorùbá",
    "zu": "Zulu - isiZulu"
};
const language_List = [];
var i = 1;
for (var lan in languages_list) {
    // console.log("lan",lan,"\n");
    language_List.push({ "value": i, "label": languages_list[lan] });
    i++;

}
const tagslist = [
    {
        "Web Development": [
            { "value": 1, "label": "HTML" },
            { "value": 2, "label": "CSS" },
            { "value": 3, "label": "JavaScript" },
            { "value": 4, "label": "PHP" },
            { "value": 5, "label": "Python" },
            { "value": 6, "label": "Ruby" },
            { "value": 7, "label": "Java" },
        ]
    },
    {
        "Mobile Development": [
            { "value": 1, "label": "Android" },
            { "value": 2, "label": "iOS" },
            { "value": 3, "label": "React Native" },
            { "value": 4, "label": "Flutter" },
            { "value": 5, "label": "Ionic" },
            { "value": 6, "label": "PhoneGap" },
            { "value": 7, "label": "Xamarin" },
        ]
    },
    {
        "Desktop Development": [
            { "value": 1, "label": "C++" },
            { "value": 2, "label": "C#" },
            { "value": 3, "label": "Java" },
            { "value": 4, "label": "Python" },
            { "value": 5, "label": "Ruby" },
            { "value": 6, "label": "PHP" },
            { "value": 7, "label": "Swift" },
        ]
    },
    {
        "Data Science": [
            { "value": 1, "label": "Python" },
            { "value": 2, "label": "Tensor Flow" },
            { "value": 3, "label": "R" },
            { "value": 4, "label": "PyCharm" },
            { "value": 5, "label": "Jupyter Notebook" },
            { "value": 6, "label": "Matlab" },
            { "value": 7, "label": "SAS" },
        ]
    },
    {
        "Machine Learning": [
            { "value": 1, "label": "Python" },
            { "value": 2, "label": "Tensor Flow" },
            { "value": 3, "label": "R" },
            { "value": 4, "label": "PyCharm" },
            { "value": 5, "label": "Jupyter Notebook" },
            { "value": 6, "label": "Matlab" },
            { "value": 7, "label": "SAS" },
        ]
    },
    {
        "Artificial Intelligence": [
            { "value": 1, "label": "Python" },
            { "value": 2, "label": "Tensor Flow" },
            { "value": 3, "label": "R" },
            { "value": 4, "label": "PyCharm" },
            { "value": 5, "label": "Jupyter Notebook" },
            { "value": 6, "label": "Matlab" },
            { "value": 7, "label": "SAS" },
        ]
    },
    {
        "Cloud Computing": [
            { "value": 1, "label": "AWS" },
            { "value": 2, "label": "Azure" },
            { "value": 3, "label": "Google Cloud" },
            { "value": 4, "label": "IBM Cloud" },
            { "value": 5, "label": "Oracle Cloud" },
            { "value": 6, "label": "Salesforce" },
            { "value": 7, "label": "VMware" },
        ]
    },
    {
        "Cyber Security": [
            { "value": 1, "label": "Wireshark" },
            { "value": 2, "label": "Kali Linux" },
            { "value": 3, "label": "John the Ripper" },
            { "value": 4, "label": "Nmap" },
            { "value": 5, "label": "Metasploit" },
            { "value": 6, "label": "Burp Suite" },
            { "value": 7, "label": "Nessus" },
        ]
    },
    {
        "Blockchain": [
            { "value": 1, "label": "Ethereum" },
            { "value": 2, "label": "Hyperledger" },
            { "value": 3, "label": "Bitcoin" },
            { "value": 4, "label": "Ripple" },
            { "value": 5, "label": "EOS" },
            { "value": 6, "label": "Stellar" },
            { "value": 7, "label": "Cardano" },
        ]
    },
    {

        "Internet of Things": [
            { "value": 1, "label": "Arduino" },
            { "value": 2, "label": "Raspberry Pi" },
            { "value": 3, "label": "ESP32" },
            { "value": 4, "label": "ESP8266" },
            { "value": 5, "label": "BeagleBone" },
            { "value": 6, "label": "Intel Edison" },
            { "value": 7, "label": "NXP FRDM" },
        ]
    },
    {
        "Game Development": [
            { "value": 1, "label": "Unity" },
            { "value": 2, "label": "Unreal Engine" },
            { "value": 3, "label": "Cocos2d-x" },
            { "value": 4, "label": "GameMaker" },
            { "value": 5, "label": "Construct 2" },
            { "value": 6, "label": "Stencyl" },
            { "value": 7, "label": "GameSalad" },
        ]
    },
    {
        "UI/UX Design": [
            { "value": 1, "label": "Adobe XD" },
            { "value": 2, "label": "Sketch" },
            { "value": 3, "label": "Figma" },
            { "value": 4, "label": "InVision" },
            { "value": 5, "label": "Marvel" },
            { "value": 6, "label": "Adobe Photoshop" },
            { "value": 7, "label": "Adobe Illustrator" },
        ]
    },
    {
        "Graphic Design": [
            { "value": 1, "label": "Adobe Photoshop" },
            { "value": 2, "label": "Adobe Illustrator" },
            { "value": 3, "label": "Adobe InDesign" },
            { "value": 4, "label": "Adobe Lightroom" },
            { "value": 5, "label": "Adobe Premiere Pro" },
            { "value": 6, "label": "Adobe After Effects" },
            { "value": 7, "label": "Adobe Animate" },
        ]
    },
    {

        "Video Editing": [
            { "value": 1, "label": "Adobe Premiere Pro" },
            { "value": 2, "label": "Adobe After Effects" },
            { "value": 3, "label": "Adobe Animate" },
            { "value": 4, "label": "Adobe Photoshop" },
            { "value": 5, "label": "Adobe Illustrator" },
            { "value": 6, "label": "Adobe InDesign" },
            { "value": 7, "label": "Adobe Lightroom" },
        ]
    },
    {
        "Animation": [
            { "value": 1, "label": "Adobe After Effects" },
            { "value": 2, "label": "Adobe Animate" },
            { "value": 3, "label": "Adobe Premiere Pro" },
            { "value": 4, "label": "Adobe Photoshop" },
            { "value": 5, "label": "Adobe Illustrator" },
            { "value": 6, "label": "Adobe InDesign" },
            { "value": 7, "label": "Adobe Lightroom" },
        ]
    },
    {
        "Digital Marketing": [
            { "value": 1, "label": "Google Analytics" },
            { "value": 2, "label": "Google AdWords" },
            { "value": 3, "label": "Google Tag Manager" },
            { "value": 4, "label": "Google Data Studio" },
            { "value": 5, "label": "Google Optimize" },
            { "value": 6, "label": "Google Search Console" },
            { "value": 7, "label": "Google My Business" },
        ]
    },
    {
        "Content Writing": [
            { "value": 1, "label": "WordPress" },
            { "value": 2, "label": "Blogger" },
            { "value": 3, "label": "Tumblr" },
            { "value": 4, "label": "Medium" },
            { "value": 5, "label": "Wix" },
            { "value": 6, "label": "Weebly" },
            { "value": 7, "label": "Squarespace" },
        ]
    },
    {
        "Business": [
            { "value": 1, "label": "Microsoft Excel" },
            { "value": 2, "label": "Microsoft Word" },
            { "value": 3, "label": "Microsoft PowerPoint" },
            { "value": 4, "label": "Microsoft Outlook" },
            { "value": 5, "label": "Microsoft OneNote" },
            { "value": 6, "label": "Microsoft Access" },
            { "value": 7, "label": "Microsoft Publisher" },
        ]
    },
    {
        "Other": [
            { "value": 1, "label": "HTML" },
            { "value": 2, "label": "CSS" },
            { "value": 3, "label": "JavaScript" },
            { "value": 4, "label": "PHP" },
            { "value": 5, "label": "Python" },
            { "value": 6, "label": "Ruby" },
            { "value": 7, "label": "Java" },
            { "value": 1, "label": "Android" },
            { "value": 2, "label": "iOS" },
            { "value": 3, "label": "React Native" },
            { "value": 4, "label": "Flutter" },
            { "value": 5, "label": "Ionic" },
            { "value": 6, "label": "PhoneGap" },
            { "value": 7, "label": "Xamarin" },
            { "value": 1, "label": "C++" },
            { "value": 2, "label": "C#" },
            { "value": 3, "label": "Java" },
            { "value": 4, "label": "Python" },
            { "value": 5, "label": "Ruby" },
            { "value": 6, "label": "PHP" },
            { "value": 7, "label": "Swift" },
            { "value": 1, "label": "MySQL" },
            { "value": 1, "label": "Arduino" },
            { "value": 2, "label": "Raspberry Pi" },
            { "value": 3, "label": "ESP32" },
            { "value": 4, "label": "ESP8266" },
            { "value": 5, "label": "BeagleBone" },
            { "value": 6, "label": "Intel Edison" },
            { "value": 7, "label": "NXP FRDM" },
        ]
    }

]

const numbers = [
    { "value": 1, "label": "1" },
    { "value": 2, "label": "2" },
    { "value": 3, "label": "3" },
    { "value": 4, "label": "4" },
    { "value": 5, "label": "5" },
    { "value": 6, "label": "6" },
    { "value": 7, "label": "7" },
    { "value": 8, "label": "8" },
    { "value": 9, "label": "9" },
    { "value": 10, "label": "10" },
    { "value": 11, "label": "11" },
    { "value": 12, "label": "12" },
    { "value": 13, "label": "13" },
    { "value": 14, "label": "14" },
    { "value": 15, "label": "15" },
    { "value": 16, "label": "16" },
    { "value": 17, "label": "17" },
    { "value": 18, "label": "18" },
    { "value": 19, "label": "19" },
    { "value": 20, "label": "20" },
]

export const numebers = numbers;
export const languageList = language_List;
export const tagsList = tagslist;