export const gigCategories = [
    { value: '1', label: 'Web Development' },
    { value: '2', label: 'Mobile Development' },
    { value: '3', label: 'Desktop Development' },
    { value: '4', label: 'Data Science' },
    { value: '5', label: 'Machine Learning' },
    { value: '6', label: 'Artificial Intelligence' },
    { value: '7', label: 'Cloud Computing' },
    { value: '8', label: 'Cyber Security' },
    { value: '9', label: 'Blockchain' },
    { value: '10', label: 'Internet of Things' },
    { value: '11', label: 'Game Development' },
    { value: '12', label: 'UI/UX Design' },
    { value: '13', label: 'Graphic Design' },
    { value: '14', label: 'Video Editing' },
    { value: '15', label: 'Animation' },
    { value: '16', label: 'Digital Marketing' },
    { value: '17', label: 'Content Writing' },
    { value: '18', label: 'Business' },
    { value: '19', label: 'Other' },
]
const languages_list = {
    "af": "Afrikaans",
    "sq": "Albanian - shqip",
    "am": "Amharic - አማርኛ",
    "ar": "Arabic - العربية",
    "an": "Aragonese - aragonés",
    "hy": "Armenian - հայերեն",
    "ast": "Asturian - asturianu",
    "az": "Azerbaijani - azərbaycan dili",
    "eu": "Basque - euskara",
    "be": "Belarusian - беларуская",
    "bn": "Bengali - বাংলা",
    "bs": "Bosnian - bosanski",
    "br": "Breton - brezhoneg",
    "bg": "Bulgarian - български",
    "ca": "Catalan - català",
    "ckb": "Central Kurdish - کوردی (دەستنوسی عەرەبی)",
    "zh": "Chinese - 中文",
    "zh-HK": "Chinese (Hong Kong) - 中文（香港）",
    "zh-CN": "Chinese (Simplified) - 中文（简体）",
    "zh-TW": "Chinese (Traditional) - 中文（繁體）",
    "co": "Corsican",
    "hr": "Croatian - hrvatski",
    "cs": "Czech - čeština",
    "da": "Danish - dansk",
    "nl": "Dutch - Nederlands",
    "en": "English",
    "en-AU": "English (Australia)",
    "en-CA": "English (Canada)",
    "en-IN": "English (India)",
    "en-NZ": "English (New Zealand)",
    "en-ZA": "English (South Africa)",
    "en-GB": "English (United Kingdom)",
    "en-US": "English (United States)",
    "eo": "Esperanto - esperanto",
    "et": "Estonian - eesti",
    "fo": "Faroese - føroyskt",
    "fil": "Filipino",
    "fi": "Finnish - suomi",
    "fr": "French - français",
    "fr-CA": "French (Canada) - français (Canada)",
    "fr-FR": "French (France) - français (France)",
    "fr-CH": "French (Switzerland) - français (Suisse)",
    "gl": "Galician - galego",
    "ka": "Georgian - ქართული",
    "de": "German - Deutsch",
    "de-AT": "German (Austria) - Deutsch (Österreich)",
    "de-DE": "German (Germany) - Deutsch (Deutschland)",
    "de-LI": "German (Liechtenstein) - Deutsch (Liechtenstein)",
    "de-CH": "German (Switzerland) - Deutsch (Schweiz)",
    "el": "Greek - Ελληνικά",
    "gn": "Guarani",
    "gu": "Gujarati - ગુજરાતી",
    "ha": "Hausa",
    "haw": "Hawaiian - ʻŌlelo Hawaiʻi",
    "he": "Hebrew - עברית",
    "hi": "Hindi - हिन्दी",
    "hu": "Hungarian - magyar",
    "is": "Icelandic - íslenska",
    "id": "Indonesian - Indonesia",
    "ia": "Interlingua",
    "ga": "Irish - Gaeilge",
    "it": "Italian - italiano",
    "it-IT": "Italian (Italy) - italiano (Italia)",
    "it-CH": "Italian (Switzerland) - italiano (Svizzera)",
    "ja": "Japanese - 日本語",
    "kn": "Kannada - ಕನ್ನಡ",
    "kk": "Kazakh - қазақ тілі",
    "km": "Khmer - ខ្មែរ",
    "ko": "Korean - 한국어",
    "ku": "Kurdish - Kurdî",
    "ky": "Kyrgyz - кыргызча",
    "lo": "Lao - ລາວ",
    "la": "Latin",
    "lv": "Latvian - latviešu",
    "ln": "Lingala - lingála",
    "lt": "Lithuanian - lietuvių",
    "mk": "Macedonian - македонски",
    "ms": "Malay - Bahasa Melayu",
    "ml": "Malayalam - മലയാളം",
    "mt": "Maltese - Malti",
    "mr": "Marathi - मराठी",
    "mn": "Mongolian - монгол",
    "ne": "Nepali - नेपाली",
    "no": "Norwegian - norsk",
    "nb": "Norwegian Bokmål - norsk bokmål",
    "nn": "Norwegian Nynorsk - nynorsk",
    "oc": "Occitan",
    "or": "Oriya - ଓଡ଼ିଆ",
    "om": "Oromo - Oromoo",
    "ps": "Pashto - پښتو",
    "fa": "Persian - فارسی",
    "pl": "Polish - polski",
    "pt": "Portuguese - português",
    "pt-BR": "Portuguese (Brazil) - português (Brasil)",
    "pt-PT": "Portuguese (Portugal) - português (Portugal)",
    "pa": "Punjabi - ਪੰਜਾਬੀ",
    "qu": "Quechua",
    "ro": "Romanian - română",
    "mo": "Romanian (Moldova) - română (Moldova)",
    "rm": "Romansh - rumantsch",
    "ru": "Russian - русский",
    "gd": "Scottish Gaelic",
    "sr": "Serbian - српски",
    "sh": "Serbo-Croatian - Srpskohrvatski",
    "sn": "Shona - chiShona",
    "sd": "Sindhi",
    "si": "Sinhala - සිංහල",
    "sk": "Slovak - slovenčina",
    "sl": "Slovenian - slovenščina",
    "so": "Somali - Soomaali",
    "st": "Southern Sotho",
    "es": "Spanish - español",
    "es-AR": "Spanish (Argentina) - español (Argentina)",
    "es-419": "Spanish (Latin America) - español (Latinoamérica)",
    "es-MX": "Spanish (Mexico) - español (México)",
    "es-ES": "Spanish (Spain) - español (España)",
    "es-US": "Spanish (United States) - español (Estados Unidos)",
    "su": "Sundanese",
    "sw": "Swahili - Kiswahili",
    "sv": "Swedish - svenska",
    "tg": "Tajik - тоҷикӣ",
    "ta": "Tamil - தமிழ்",
    "tt": "Tatar",
    "te": "Telugu - తెలుగు",
    "th": "Thai - ไทย",
    "ti": "Tigrinya - ትግርኛ",
    "to": "Tongan - lea fakatonga",
    "tr": "Turkish - Türkçe",
    "tk": "Turkmen",
    "tw": "Twi",
    "uk": "Ukrainian - українська",
    "ur": "Urdu - اردو",
    "ug": "Uyghur",
    "uz": "Uzbek - o‘zbek",
    "vi": "Vietnamese - Tiếng Việt",
    "wa": "Walloon - wa",
    "cy": "Welsh - Cymraeg",
    "fy": "Western Frisian",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "yo": "Yoruba - Èdè Yorùbá",
    "zu": "Zulu - isiZulu"
};
const language_List = [];
var i = 1;
for (var lan in languages_list) {
    // console.log("lan",lan,"\n");
    language_List.push({ "value": i, "label": languages_list[lan] });
    i++;

}
const tagslist = [
    {
        "Web Development": [
            { "value": 1, "label": "HTML" },
            { "value": 2, "label": "CSS" },
            { "value": 3, "label": "JavaScript" },
            { "value": 4, "label": "PHP" },
            { "value": 5, "label": "Python" },
            { "value": 6, "label": "Ruby" },
            { "value": 7, "label": "Java" },
        ]
    },
    {
        "Mobile Development": [
            { "value": 1, "label": "Android" },
            { "value": 2, "label": "iOS" },
            { "value": 3, "label": "React Native" },
            { "value": 4, "label": "Flutter" },
            { "value": 5, "label": "Ionic" },
            { "value": 6, "label": "PhoneGap" },
            { "value": 7, "label": "Xamarin" },
        ]
    },
    {
        "Desktop Development": [
            { "value": 1, "label": "C++" },
            { "value": 2, "label": "C#" },
            { "value": 3, "label": "Java" },
            { "value": 4, "label": "Python" },
            { "value": 5, "label": "Ruby" },
            { "value": 6, "label": "PHP" },
            { "value": 7, "label": "Swift" },
        ]
    },
    {
        "Data Science": [
            { "value": 1, "label": "Python" },
            { "value": 2, "label": "Tensor Flow" },
            { "value": 3, "label": "R" },
            { "value": 4, "label": "PyCharm" },
            { "value": 5, "label": "Jupyter Notebook" },
            { "value": 6, "label": "Matlab" },
            { "value": 7, "label": "SAS" },
        ]
    },
    {
        "Machine Learning": [
            { "value": 1, "label": "Python" },
            { "value": 2, "label": "Tensor Flow" },
            { "value": 3, "label": "R" },
            { "value": 4, "label": "PyCharm" },
            { "value": 5, "label": "Jupyter Notebook" },
            { "value": 6, "label": "Matlab" },
            { "value": 7, "label": "SAS" },
        ]
    },
    {
        "Artificial Intelligence": [
            { "value": 1, "label": "Python" },
            { "value": 2, "label": "Tensor Flow" },
            { "value": 3, "label": "R" },
            { "value": 4, "label": "PyCharm" },
            { "value": 5, "label": "Jupyter Notebook" },
            { "value": 6, "label": "Matlab" },
            { "value": 7, "label": "SAS" },
        ]
    },
    {
        "Cloud Computing": [
            { "value": 1, "label": "AWS" },
            { "value": 2, "label": "Azure" },
            { "value": 3, "label": "Google Cloud" },
            { "value": 4, "label": "IBM Cloud" },
            { "value": 5, "label": "Oracle Cloud" },
            { "value": 6, "label": "Salesforce" },
            { "value": 7, "label": "VMware" },
        ]
    },
    {
        "Cyber Security": [
            { "value": 1, "label": "Wireshark" },
            { "value": 2, "label": "Kali Linux" },
            { "value": 3, "label": "John the Ripper" },
            { "value": 4, "label": "Nmap" },
            { "value": 5, "label": "Metasploit" },
            { "value": 6, "label": "Burp Suite" },
            { "value": 7, "label": "Nessus" },
        ]
    },
    {
        "Blockchain": [
            { "value": 1, "label": "Ethereum" },
            { "value": 2, "label": "Hyperledger" },
            { "value": 3, "label": "Bitcoin" },
            { "value": 4, "label": "Ripple" },
            { "value": 5, "label": "EOS" },
            { "value": 6, "label": "Stellar" },
            { "value": 7, "label": "Cardano" },
        ]
    },
    {

        "Internet of Things": [
            { "value": 1, "label": "Arduino" },
            { "value": 2, "label": "Raspberry Pi" },
            { "value": 3, "label": "ESP32" },
            { "value": 4, "label": "ESP8266" },
            { "value": 5, "label": "BeagleBone" },
            { "value": 6, "label": "Intel Edison" },
            { "value": 7, "label": "NXP FRDM" },
        ]
    },
    {
        "Game Development": [
            { "value": 1, "label": "Unity" },
            { "value": 2, "label": "Unreal Engine" },
            { "value": 3, "label": "Cocos2d-x" },
            { "value": 4, "label": "GameMaker" },
            { "value": 5, "label": "Construct 2" },
            { "value": 6, "label": "Stencyl" },
            { "value": 7, "label": "GameSalad" },
        ]
    },
    {
        "UI/UX Design": [
            { "value": 1, "label": "Adobe XD" },
            { "value": 2, "label": "Sketch" },
            { "value": 3, "label": "Figma" },
            { "value": 4, "label": "InVision" },
            { "value": 5, "label": "Marvel" },
            { "value": 6, "label": "Adobe Photoshop" },
            { "value": 7, "label": "Adobe Illustrator" },
        ]
    },
    {
        "Graphic Design": [
            { "value": 1, "label": "Adobe Photoshop" },
            { "value": 2, "label": "Adobe Illustrator" },
            { "value": 3, "label": "Adobe InDesign" },
            { "value": 4, "label": "Adobe Lightroom" },
            { "value": 5, "label": "Adobe Premiere Pro" },
            { "value": 6, "label": "Adobe After Effects" },
            { "value": 7, "label": "Adobe Animate" },
        ]
    },
    {

        "Video Editing": [
            { "value": 1, "label": "Adobe Premiere Pro" },
            { "value": 2, "label": "Adobe After Effects" },
            { "value": 3, "label": "Adobe Animate" },
            { "value": 4, "label": "Adobe Photoshop" },
            { "value": 5, "label": "Adobe Illustrator" },
            { "value": 6, "label": "Adobe InDesign" },
            { "value": 7, "label": "Adobe Lightroom" },
        ]
    },
    {
        "Animation": [
            { "value": 1, "label": "Adobe After Effects" },
            { "value": 2, "label": "Adobe Animate" },
            { "value": 3, "label": "Adobe Premiere Pro" },
            { "value": 4, "label": "Adobe Photoshop" },
            { "value": 5, "label": "Adobe Illustrator" },
            { "value": 6, "label": "Adobe InDesign" },
            { "value": 7, "label": "Adobe Lightroom" },
        ]
    },
    {
        "Digital Marketing": [
            { "value": 1, "label": "Google Analytics" },
            { "value": 2, "label": "Google AdWords" },
            { "value": 3, "label": "Google Tag Manager" },
            { "value": 4, "label": "Google Data Studio" },
            { "value": 5, "label": "Google Optimize" },
            { "value": 6, "label": "Google Search Console" },
            { "value": 7, "label": "Google My Business" },
        ]
    },
    {
        "Content Writing": [
            { "value": 1, "label": "WordPress" },
            { "value": 2, "label": "Blogger" },
            { "value": 3, "label": "Tumblr" },
            { "value": 4, "label": "Medium" },
            { "value": 5, "label": "Wix" },
            { "value": 6, "label": "Weebly" },
            { "value": 7, "label": "Squarespace" },
        ]
    },
    {
        "Business": [
            { "value": 1, "label": "Microsoft Excel" },
            { "value": 2, "label": "Microsoft Word" },
            { "value": 3, "label": "Microsoft PowerPoint" },
            { "value": 4, "label": "Microsoft Outlook" },
            { "value": 5, "label": "Microsoft OneNote" },
            { "value": 6, "label": "Microsoft Access" },
            { "value": 7, "label": "Microsoft Publisher" },
        ]
    },
    {
        "Other": [
            { "value": 1, "label": "HTML" },
            { "value": 2, "label": "CSS" },
            { "value": 3, "label": "JavaScript" },
            { "value": 4, "label": "PHP" },
            { "value": 5, "label": "Python" },
            { "value": 6, "label": "Ruby" },
            { "value": 7, "label": "Java" },
            { "value": 1, "label": "Android" },
            { "value": 2, "label": "iOS" },
            { "value": 3, "label": "React Native" },
            { "value": 4, "label": "Flutter" },
            { "value": 5, "label": "Ionic" },
            { "value": 6, "label": "PhoneGap" },
            { "value": 7, "label": "Xamarin" },
            { "value": 1, "label": "C++" },
            { "value": 2, "label": "C#" },
            { "value": 3, "label": "Java" },
            { "value": 4, "label": "Python" },
            { "value": 5, "label": "Ruby" },
            { "value": 6, "label": "PHP" },
            { "value": 7, "label": "Swift" },
            { "value": 1, "label": "MySQL" },
            { "value": 1, "label": "Arduino" },
            { "value": 2, "label": "Raspberry Pi" },
            { "value": 3, "label": "ESP32" },
            { "value": 4, "label": "ESP8266" },
            { "value": 5, "label": "BeagleBone" },
            { "value": 6, "label": "Intel Edison" },
            { "value": 7, "label": "NXP FRDM" },
        ]
    }

]

const numbers = [
    { "value": 1, "label": "1" },
    { "value": 2, "label": "2" },
    { "value": 3, "label": "3" },
    { "value": 4, "label": "4" },
    { "value": 5, "label": "5" },
    { "value": 6, "label": "6" },
    { "value": 7, "label": "7" },
    { "value": 8, "label": "8" },
    { "value": 9, "label": "9" },
    { "value": 10, "label": "10" },
    { "value": 11, "label": "11" },
    { "value": 12, "label": "12" },
    { "value": 13, "label": "13" },
    { "value": 14, "label": "14" },
    { "value": 15, "label": "15" },
    { "value": 16, "label": "16" },
    { "value": 17, "label": "17" },
    { "value": 18, "label": "18" },
    { "value": 19, "label": "19" },
    { "value": 20, "label": "20" },
]

const genderOption = [
    { "value": 1, "label": "Male" },
    { "value": 2, "label": "Female" },
]

const humanLanguage = [
    { code: 'ab', name: 'Abkhazian' },
    { code: 'aa', name: 'Afar' },
    { code: 'af', name: 'Afrikaans' },
    { code: 'ak', name: 'Akan' },
    { code: 'sq', name: 'Albanian' },
    { code: 'am', name: 'Amharic' },
    { code: 'ar', name: 'Arabic' },
    { code: 'an', name: 'Aragonese' },
    { code: 'hy', name: 'Armenian' },
    { code: 'as', name: 'Assamese' },
    { code: 'av', name: 'Avaric' },
    { code: 'ae', name: 'Avestan' },
    { code: 'ay', name: 'Aymara' },
    { code: 'az', name: 'Azerbaijani' },
    { code: 'bm', name: 'Bambara' },
    { code: 'ba', name: 'Bashkir' },
    { code: 'eu', name: 'Basque' },
    { code: 'be', name: 'Belarusian' },
    { code: 'bn', name: 'Bengali' },
    { code: 'bh', name: 'Bihari languages' },
    { code: 'bi', name: 'Bislama' },
    { code: 'bs', name: 'Bosnian' },
    { code: 'br', name: 'Breton' },
    { code: 'bg', name: 'Bulgarian' },
    { code: 'my', name: 'Burmese' },
    { code: 'ca', name: 'Catalan, Valencian' },
    { code: 'km', name: 'Central Khmer' },
    { code: 'ch', name: 'Chamorro' },
    { code: 'ce', name: 'Chechen' },
    { code: 'ny', name: 'Chichewa, Chewa, Nyanja' },
    { code: 'zh', name: 'Chinese' },
    { code: 'cu', name: 'Church Slavonic, Old Bulgarian, Old Church Slavonic' },
    { code: 'cv', name: 'Chuvash' },
    { code: 'kw', name: 'Cornish' },
    { code: 'co', name: 'Corsican' },
    { code: 'cr', name: 'Cree' },
    { code: 'hr', name: 'Croatian' },
    { code: 'cs', name: 'Czech' },
    { code: 'da', name: 'Danish' },
    { code: 'dv', name: 'Divehi, Dhivehi, Maldivian' },
    { code: 'nl', name: 'Dutch, Flemish' },
    { code: 'dz', name: 'Dzongkha' },
    { code: 'en', name: 'English' },
    { code: 'eo', name: 'Esperanto' },
    { code: 'et', name: 'Estonian' },
    { code: 'ee', name: 'Ewe' },
    { code: 'fo', name: 'Faroese' },
    { code: 'fj', name: 'Fijian' },
    { code: 'fi', name: 'Finnish' },
    { code: 'fr', name: 'French' },
    { code: 'ff', name: 'Fulah' },
    { code: 'gd', name: 'Gaelic, Scottish Gaelic' },
    { code: 'gl', name: 'Galician' },
    { code: 'lg', name: 'Ganda' },
    { code: 'ka', name: 'Georgian' },
    { code: 'de', name: 'German' },
    { code: 'ki', name: 'Gikuyu, Kikuyu' },
    { code: 'el', name: 'Greek (Modern)' },
    { code: 'kl', name: 'Greenlandic, Kalaallisut' },
    { code: 'gn', name: 'Guarani' },
    { code: 'gu', name: 'Gujarati' },
    { code: 'ht', name: 'Haitian, Haitian Creole' },
    { code: 'ha', name: 'Hausa' },
    { code: 'he', name: 'Hebrew' },
    { code: 'hz', name: 'Herero' },
    { code: 'hi', name: 'Hindi' },
    { code: 'ho', name: 'Hiri Motu' },
    { code: 'hu', name: 'Hungarian' },
    { code: 'is', name: 'Icelandic' },
    { code: 'io', name: 'Ido' },
    { code: 'ig', name: 'Igbo' },
    { code: 'id', name: 'Indonesian' },
    { code: 'ia', name: 'Interlingua (International Auxiliary Language Association)' },
    { code: 'ie', name: 'Interlingue' },
    { code: 'iu', name: 'Inuktitut' },
    { code: 'ik', name: 'Inupiaq' },
    { code: 'ga', name: 'Irish' },
    { code: 'it', name: 'Italian' },
    { code: 'ja', name: 'Japanese' },
    { code: 'jv', name: 'Javanese' },
    { code: 'kn', name: 'Kannada' },
    { code: 'kr', name: 'Kanuri' },
    { code: 'ks', name: 'Kashmiri' },
    { code: 'kk', name: 'Kazakh' },
    { code: 'rw', name: 'Kinyarwanda' },
    { code: 'kv', name: 'Komi' },
    { code: 'kg', name: 'Kongo' },
    { code: 'ko', name: 'Korean' },
    { code: 'kj', name: 'Kwanyama, Kuanyama' },
    { code: 'ku', name: 'Kurdish' },
    { code: 'ky', name: 'Kyrgyz' },
    { code: 'lo', name: 'Lao' },
    { code: 'la', name: 'Latin' },
    { code: 'lv', name: 'Latvian' },
    { code: 'lb', name: 'Letzeburgesch, Luxembourgish' },
    { code: 'li', name: 'Limburgish, Limburgan, Limburger' },
    { code: 'ln', name: 'Lingala' },
    { code: 'lt', name: 'Lithuanian' },
    { code: 'lu', name: 'Luba-Katanga' },
    { code: 'mk', name: 'Macedonian' },
    { code: 'mg', name: 'Malagasy' },
    { code: 'ms', name: 'Malay' },
    { code: 'ml', name: 'Malayalam' },
    { code: 'mt', name: 'Maltese' },
    { code: 'gv', name: 'Manx' },
    { code: 'mi', name: 'Maori' },
    { code: 'mr', name: 'Marathi' },
    { code: 'mh', name: 'Marshallese' },
    { code: 'ro', name: 'Moldovan, Moldavian, Romanian' },
    { code: 'mn', name: 'Mongolian' },
    { code: 'na', name: 'Nauru' },
    { code: 'nv', name: 'Navajo, Navaho' },
    { code: 'nd', name: 'Northern Ndebele' },
    { code: 'ng', name: 'Ndonga' },
    { code: 'ne', name: 'Nepali' },
    { code: 'se', name: 'Northern Sami' },
    { code: 'no', name: 'Norwegian' },
    { code: 'nb', name: 'Norwegian Bokmål' },
    { code: 'nn', name: 'Norwegian Nynorsk' },
    { code: 'ii', name: 'Nuosu, Sichuan Yi' },
    { code: 'oc', name: 'Occitan (post 1500)' },
    { code: 'oj', name: 'Ojibwa' },
    { code: 'or', name: 'Oriya' },
    { code: 'om', name: 'Oromo' },
    { code: 'os', name: 'Ossetian, Ossetic' },
    { code: 'pi', name: 'Pali' },
    { code: 'pa', name: 'Panjabi, Punjabi' },
    { code: 'ps', name: 'Pashto, Pushto' },
    { code: 'fa', name: 'Persian' },
    { code: 'pl', name: 'Polish' },
    { code: 'pt', name: 'Portuguese' },
    { code: 'qu', name: 'Quechua' },
    { code: 'rm', name: 'Romansh' },
    { code: 'rn', name: 'Rundi' },
    { code: 'ru', name: 'Russian' },
    { code: 'sm', name: 'Samoan' },
    { code: 'sg', name: 'Sango' },
    { code: 'sa', name: 'Sanskrit' },
    { code: 'sc', name: 'Sardinian' },
    { code: 'sr', name: 'Serbian' },
    { code: 'sn', name: 'Shona' },
    { code: 'sd', name: 'Sindhi' },
    { code: 'si', name: 'Sinhala, Sinhalese' },
    { code: 'sk', name: 'Slovak' },
    { code: 'sl', name: 'Slovenian' },
    { code: 'so', name: 'Somali' },
    { code: 'st', name: 'Sotho, Southern' },
    { code: 'nr', name: 'South Ndebele' },
    { code: 'es', name: 'Spanish, Castilian' },
    { code: 'su', name: 'Sundanese' },
    { code: 'sw', name: 'Swahili' },
    { code: 'ss', name: 'Swati' },
    { code: 'sv', name: 'Swedish' },
    { code: 'tl', name: 'Tagalog' },
    { code: 'ty', name: 'Tahitian' },
    { code: 'tg', name: 'Tajik' },
    { code: 'ta', name: 'Tamil' },
    { code: 'tt', name: 'Tatar' },
    { code: 'te', name: 'Telugu' },
    { code: 'th', name: 'Thai' },
    { code: 'bo', name: 'Tibetan' },
    { code: 'ti', name: 'Tigrinya' },
    { code: 'to', name: 'Tonga (Tonga Islands)' },
    { code: 'ts', name: 'Tsonga' },
    { code: 'tn', name: 'Tswana' },
    { code: 'tr', name: 'Turkish' },
    { code: 'tk', name: 'Turkmen' },
    { code: 'tw', name: 'Twi' },
    { code: 'ug', name: 'Uighur, Uyghur' },
    { code: 'uk', name: 'Ukrainian' },
    { code: 'ur', name: 'Urdu' },
    { code: 'uz', name: 'Uzbek' },
    { code: 've', name: 'Venda' },
    { code: 'vi', name: 'Vietnamese' },
    { code: 'vo', name: 'Volap_k' },
    { code: 'wa', name: 'Walloon' },
    { code: 'cy', name: 'Welsh' },
    { code: 'fy', name: 'Western Frisian' },
    { code: 'wo', name: 'Wolof' },
    { code: 'xh', name: 'Xhosa' },
    { code: 'yi', name: 'Yiddish' },
    { code: 'yo', name: 'Yoruba' },
    { code: 'za', name: 'Zhuang, Chuang' },
    { code: 'zu', name: 'Zulu' }
];
const lanuageProficiencyList = [
    { code: 'native', name: 'Native' },
    { code: 'intermediate', name: 'intermediate' },
    { code: 'fluent', name: 'Fluent' },
];

export const languageProficiency = lanuageProficiencyList;
export const humanLanguages = humanLanguage;
export const genderOptions = genderOption;
export const numebers = numbers;
export const languageList = language_List;
export const tagsList = tagslist;